### ISSUE TITLE
Support for Indexes

### ISSUE THREAD

**Issue by dmarcelino** [appscot/waterline-orientdb#2]
Currently indexes don't seem to be supported

**Comment by rodrigorn** [comment]
It could be great to have at least unique indexes

**Comment by dmarcelino** [comment]
Agreed @rodrigorn, I'll take a look at it soon.

**Comment by rodrigorn** [comment]
how can I help @dmarcelino?

**Comment by dmarcelino** [comment]
Thanks @rodrigorn. Can you take a look at PR #36? The key changes were done by @naderio and I think it will make you happy.
