### ISSUE TITLE
Unrecognized Types

### ISSUE THREAD

**Issue by tommykennedy** [appscot/waterline-orientdb#44]
Hi

I am getting an recognised type for attribute email that is declared in my model.

var User = {
  // Enforce model schema in the case of schemaless databases
  schema: true,

  attributes: {
    id: { type: 'string', primaryKey: true, columnName: '@rid'},
    username  : { type: 'string', unique: true },
    email     : { type: 'email',  unique: true },
    passports : { collection: 'Passport', via: 'user'}
  }
};

java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.metadata.schema.OType.EMAIL
java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.metadata.schema.OType.EMAIL

Sails-orientdb didn't have a problem with this. Also I am using passportjs for authentication and getting unrecginiuzed types alphanumeric and alphanumeric dashed.

Regards,
Tom

**Comment by dmarcelino** [comment]
Hi @tommykennedy,

As far as I know `sails-orientdb` does not create class properties in OrientDB hence this issue never happens as it's operating schemaless. That's my impression at least.

I've fixed it in `master`, can you please install the latest and try?

Regarding passportjs, can you please provide more info such as models, code snippets, etc? Or if you could provide an automated test such as [44-email_attribute.js](https://github.com/appscot/waterline-orientdb/blob/master/test/integration-orientdb/bugs/44-email_attribute.js) that would be super!

Cheers

**Comment by tommykennedy** [comment]
I have attached the model for Passport.js.

The attributes Alphanumeric and Alphanumericdashed are unsupported. I will try the master and let you know. 

var bcrypt = require('bcryptjs');

function hashPassword (passport, next) {
  if (passport.password) {
    bcrypt.hash(passport.password, 10, function (err, hash) {
      passport.password = hash;
      next(err, passport);
    });
  } else {
    next(null, passport);
  }
}

var Passport = {
  attributes: {
          
    id: { type: 'string', primaryKey: true, columnName: '@rid'},
    protocol: { type: 'alphanumeric', required: true },

    password: { type: 'string', minLength: 8 },
    provider   : { type: 'alphanumeric dashed' },
    identifier : { type: 'string' },
    tokens     : { type: 'json' },

    // Associations

    user: { model: 'User', required: true },

    validatePassword: function (password, next) {
      bcrypt.compare(password, this.password, next);
    }

  },

  beforeCreate: function (passport, next) {
    hashPassword(passport, next);
  },

  beforeUpdate: function (passport, next) {
    hashPassword(passport, next);
  }
};

module.exports = Passport;

**Comment by dmarcelino** [comment]
@tommykennedy, another fix pushed to master. All those should be good now. Regards.
