### ISSUE TITLE
Sample Code Many-to-Many

### ISSUE THREAD

**Issue by tommykennedy** [appscot/waterline-orientdb#55]
Dario

Are there any examples on the sails code to insert records for either Car and Vechile color examples or the Team and Stadium associations?

It would be good to grasp the concepts defined on the models demonstrated.

Tom

**Comment by dmarcelino** [comment]
Hi @tommykennedy,

I'm not aware of any sails Car and Vehicle Many-to-Many association example. There is a very good example of a Many-to-Many association (Driver and taxis) insertion in the [waterline-adapter-tests](https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/associations/manyToMany/add.js).

Team and Stadium is a Many-to-Many **through** association but all CRUD operations are handled in the same way as regular many-to-many. For some code you can check [waterline-orientdb's integration-orientdb folder](https://github.com/appscot/waterline-orientdb/blob/master/test/integration-orientdb/tests/associations/manyThrough.add.js).

Feel free to re-open the issue if these don't answer your question.

**Comment by tommykennedy** [comment]
Thanks Dario

I posted a question on stack overlow. Im having trouble understanding on how to create bi-directional edges using waterline. Help would be much appreciated. 

http://stackoverflow.com/questions/28985075/waterline-orientdb-bi-directional-edge

**Comment by dmarcelino** [comment]
Hi @tommykennedy, I've replied to this on stackoverflow, but just for reference, a working example can be found at:
https://github.com/appscot/waterline-orientdb/blob/master/example/associations/many-to-many.js
