### ISSUE TITLE
.drop() taking too long

### ISSUE THREAD

**Issue by dmarcelino** [appscot/waterline-orientdb#57]
As pointed out by @jeswinjames24 on [March 3 2015](https://gitter.im/appscot/waterline-orientdb?at=54f5bc97b1086da6119e0af2), `.drop()` is taking too long:

```
waterline-orientdb:adapter:debug DEBUG drop: app_timezone +3s
waterline-orientdb:vertex:debug DEBUG Drop [app_timezone], deleted records: 0 +5s
waterline-orientdb:document:debug DEBUG Dropped [app_timezone] +2s
waterline-orientdb:adapter:debug DEBUG describe: app_timezone +0ms
waterline-orientdb:adapter:debug DEBUG define: app_timezone +1ms
waterline-orientdb:adapter:debug DEBUG drop: st_person +3s
waterline-orientdb:vertex:debug DEBUG Drop [st_person], deleted records: 0 +6s
waterline-orientdb:document:debug DEBUG Dropped [st_person] +2s
waterline-orientdb:adapter:debug DEBUG describe: st_person +1ms
waterline-orientdb:adapter:debug DEBUG define: st_person +0ms
waterline-orientdb:adapter:debug DEBUG drop: stadiumTable +3s
waterline-orientdb:vertex:debug DEBUG Drop [stadiumTable], deleted records: 0 +4s
waterline-orientdb:document:debug DEBUG Dropped [stadiumTable] +3s
waterline-orientdb:adapter:debug DEBUG describe: stadiumTable +1ms
waterline-orientdb:adapter:debug DEBUG define: stadiumTable +0ms
waterline-orientdb:adapter:debug DEBUG drop: teamTable +3s
waterline-orientdb:vertex:debug DEBUG Drop [teamTable], deleted records: 0 +3s
waterline-orientdb:document:debug DEBUG Dropped [teamTable] +2s
waterline-orientdb:adapter:debug DEBUG describe: teamTable +0ms
waterline-orientdb:adapter:debug DEBUG define: teamTable +0ms
waterline-orientdb:adapter:debug DEBUG drop: venueTable +4s
waterline-orientdb:edge:debug DEBUG Drop [venueTable], deleted records: 0 +5s
waterline-orientdb:adapter:debug DEBUG registerConnection: staxteam_dev +0ms
waterline-orientdb:connection INFO Connecting to database... +13ms
waterline-orientdb:edge:debug DEBUG _getEdgeSides: finding vertexes for: venueTable +34ms
waterline-orientdb:edge:debug DEBUG _getEdgeSides: match found for teamRef: stadiums +2ms
waterline-orientdb:edge:debug DEBUG _getEdgeSides: match found for stadiumRef: teams +0ms
waterline-orientdb:connection INFO Database staxteam_dev found. +289ms
waterline-orientdb:adapter:debug DEBUG drop: app_gender +67ms
waterline-orientdb:vertex:debug DEBUG Drop [app_gender], deleted records: 0 +33ms
waterline-orientdb:document:debug DEBUG Dropped [app_gender] +2s
waterline-orientdb:adapter:debug DEBUG describe: app_gender +1ms
waterline-orientdb:adapter:debug DEBUG define: app_gender +1ms
waterline-orientdb:adapter:debug DEBUG drop: app_timezone +3s
waterline-orientdb:vertex:debug DEBUG Drop [app_timezone], deleted records: 0 +5s
waterline-orientdb:document:debug DEBUG Dropped [app_timezone] +2s
waterline-orientdb:adapter:debug DEBUG describe: app_timezone +0ms
waterline-orientdb:adapter:debug DEBUG define: app_timezone +1ms
waterline-orientdb:adapter:debug DEBUG drop: st_person +3s
waterline-orientdb:vertex:debug DEBUG Drop [st_person], deleted records: 0 +6s
waterline-orientdb:document:debug DEBUG Dropped [st_person] +2s
waterline-orientdb:adapter:debug DEBUG describe: st_person +1ms
waterline-orientdb:adapter:debug DEBUG define: st_person +0ms
waterline-orientdb:adapter:debug DEBUG drop: stadiumTable +3s
waterline-orientdb:vertex:debug DEBUG Drop [stadiumTable], deleted records: 0 +4s
waterline-orientdb:document:debug DEBUG Dropped [stadiumTable] +3s
waterline-orientdb:adapter:debug DEBUG describe: stadiumTable +1ms
waterline-orientdb:adapter:debug DEBUG define: stadiumTable +0ms
waterline-orientdb:adapter:debug DEBUG drop: teamTable +3s
waterline-orientdb:vertex:debug DEBUG Drop [teamTable], deleted records: 0 +3s
waterline-orientdb:document:debug DEBUG Dropped [teamTable] +2s
waterline-orientdb:adapter:debug DEBUG describe: teamTable +0ms
waterline-orientdb:adapter:debug DEBUG define: teamTable +0ms
waterline-orientdb:adapter:debug DEBUG drop: venueTable +4s
waterline-orientdb:edge:debug DEBUG Drop [venueTable], deleted records: 0 +5s
waterline-orientdb:document:debug DEBUG Dropped [venueTable] +3s
waterline-orientdb:adapter:debug DEBUG describe: venueTable +1ms
waterline-orientdb:adapter:debug DEBUG define: venueTable +0ms
waterline-orientdb:connection INFO All classes created, post processing +4s
```

Each drop is taking seconds instead of milliseconds.

**Comment by dmarcelino** [comment]
This should be mitigated by #59. @jeswinjames24, do you mind trying master with the config option [`unsafeDrop: true`](https://github.com/appscot/waterline-orientdb#connection-advanced-config-example)? Would love to see what kind of times you get as that should make the drop duration much more bearable. Thanks

**Comment by jeswinjames24** [comment]
@dmarcelino Hi, normally i use npm to install the package. How to get it from the master branch ?

**Comment by dmarcelino** [comment]
Hi @jeswinjames24, you can install an npm package from github like this:
```sh
npm appscot/waterline-orientdb
```

**Comment by jeswinjames24** [comment]
waterline-orientdb:adapter:debug DEBUG   describe: app_timezone +1ms                                                                                                                        
  waterline-orientdb:adapter:debug DEBUG   define: app_timezone +0ms                                                                                                                          
  waterline-orientdb:adapter:debug DEBUG   drop: st_person +7s                                                                                                                                
  waterline-orientdb:connection:debug DEBUG   Dropped [st_person] +2s                                                                                                                         
  waterline-orientdb:adapter:debug DEBUG   describe: st_person +1ms                                                                                                                           
  waterline-orientdb:adapter:debug DEBUG   define: st_person +0ms                                                                                                                             
  waterline-orientdb:adapter:debug DEBUG   drop: stadiumTable +6s                                                                                                                             
  waterline-orientdb:connection:debug DEBUG   Dropped [stadiumTable] +2s                                                                                                                      
  waterline-orientdb:adapter:debug DEBUG   describe: stadiumTable +0ms                                                                                                                        
  waterline-orientdb:adapter:debug DEBUG   define: stadiumTable +0ms                                                                                                                          
  waterline-orientdb:adapter:debug DEBUG   drop: teamTable +5s                                                                                                                                
  waterline-orientdb:connection:debug DEBUG   Dropped [teamTable] +2s                                                                                                                         
  waterline-orientdb:adapter:debug DEBUG   describe: teamTable +1ms                                                                                                                           
  waterline-orientdb:adapter:debug DEBUG   define: teamTable +0ms                                                                                                                             
  waterline-orientdb:adapter:debug DEBUG   drop: venueTable +5s                                                                                                                               
  waterline-orientdb:connection:debug DEBUG   Dropped [venueTable] +2s                                                                                                                        
  waterline-orientdb:adapter:debug DEBUG   describe: venueTable +1ms                                                                                                                          
  waterline-orientdb:adapter:debug DEBUG   define: venueTable +0ms                                                                                                                            
  waterline-orientdb:connection       INFO    All classes created, post processing +7s                                                                                                        
info:

**Comment by jeswinjames24** [comment]
waterline-orientdb:adapter:debug DEBUG   registerConnection: staxteam_dev +0ms                                                                                                              
  waterline-orientdb:connection       INFO    Connecting to database... +5ms                                                                                                                  
  waterline-orientdb:edge:debug DEBUG   _getEdgeSides: finding vertexes for: venueTable +52ms                                                                                                 
  waterline-orientdb:edge:debug DEBUG   _getEdgeSides: match found for teamRef: stadiums +1ms                                                                                                 
  waterline-orientdb:edge:debug DEBUG   _getEdgeSides: match found for stadiumRef: teams +0ms                                                                                                 
  waterline-orientdb:connection       INFO    Database staxteam_dev found. +94ms                                                                                                              
  waterline-orientdb:adapter:debug DEBUG   drop: app_gender +24ms                                                                                                                             
  waterline-orientdb:connection:debug DEBUG   Dropped [app_gender] +1s                                                                                                                        
  waterline-orientdb:adapter:debug DEBUG   describe: app_gender +2ms                                                                                                                          
  waterline-orientdb:adapter:debug DEBUG   define: app_gender +0ms                                                                                                                            
  waterline-orientdb:adapter:debug DEBUG   drop: app_timezone +7s                                                                                                                             
  waterline-orientdb:connection:debug DEBUG   Dropped [app_timezone] +2s   
 waterline-orientdb:adapter:debug DEBUG   describe: app_timezone +1ms                                                                                                                        
  waterline-orientdb:adapter:debug DEBUG   define: app_timezone +0ms                                                                                                                          
  waterline-orientdb:adapter:debug DEBUG   drop: st_person +7s                                                                                                                                
  waterline-orientdb:connection:debug DEBUG   Dropped [st_person] +2s                                                                                                                         
  waterline-orientdb:adapter:debug DEBUG   describe: st_person +1ms                                                                                                                           
  waterline-orientdb:adapter:debug DEBUG   define: st_person +0ms                                                                                                                             
  waterline-orientdb:adapter:debug DEBUG   drop: stadiumTable +6s                                                                                                                             
  waterline-orientdb:connection:debug DEBUG   Dropped [stadiumTable] +2s                                                                                                                      
  waterline-orientdb:adapter:debug DEBUG   describe: stadiumTable +0ms                                                                                                                        
  waterline-orientdb:adapter:debug DEBUG   define: stadiumTable +0ms                                                                                                                          
  waterline-orientdb:adapter:debug DEBUG   drop: teamTable +5s                                                                                                                                
  waterline-orientdb:connection:debug DEBUG   Dropped [teamTable] +2s                                                                                                                         
  waterline-orientdb:adapter:debug DEBUG   describe: teamTable +1ms                                                                                                                           
  waterline-orientdb:adapter:debug DEBUG   define: teamTable +0ms                                                                                                                             
  waterline-orientdb:adapter:debug DEBUG   drop: venueTable +5s                                                                                                                               
  waterline-orientdb:connection:debug DEBUG   Dropped [venueTable] +2s                                                                                                                        
  waterline-orientdb:adapter:debug DEBUG   describe: venueTable +1ms                                                                                                                          
  waterline-orientdb:adapter:debug DEBUG   define: venueTable +0ms                                                                                                                            
  waterline-orientdb:connection       INFO    All classes created, post processing +7s

**Comment by jeswinjames24** [comment]
@dmarcelino  Hi, Please note that my DB and Sails application is not on the same server. I believe this should not be an issue.

**Comment by dmarcelino** [comment]
@jeswinjames24, I see. I don't think there is much more we can do to improve this but feel free to raise an issue/PR in case you do. Closing it for now, thanks.
