### ISSUE TITLE
Association one-to-many does not force class of the link

### ISSUE THREAD

**Issue by romaintb** [appscot/waterline-orientdb#58]
Association works, but the Linked_Class is not defined.
As discussed with @dmarcelino on Gitter, a test is written for the one-to-one relation, but not for the one-to-many.

I will do a PR soon.

**Comment by romaintb** [comment]
Uh, somehow, it worked ... I suspect the console to give me hard times while web interface just works (deleting the class by console might not have really dropped it or something).

Anyway, after playing with tests, I can't find something wrong.

**Comment by dmarcelino** [comment]
I see, if you've got a working test would you mind doing a PR? It will be good too prevent regressions in the future.

**Comment by romaintb** [comment]
just did, you were quicker than me :)

**Comment by dmarcelino** [comment]
Thanks!
